baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "MENA Theater Makers Alliance"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/group.jpg"]

[menu]

[[menu.primary]]
identifier = "news"
name = "Announcements"
url = "/announcements"
weight = 1

[[menu.primary]]
identifier = "events"
name = "Convenings"
url = "/convenings"
weight = 2

[[menu.primary]]
identifier = "grants"
name = "Grants"
url = "/grants"
weight = 3

[[menu.primary]]
identifier = "resources"
name = "Resources"
url = "/resources"
weight = 4

[[menu.primary]]
identifier = "about"
name = "About Us"
url = "/about"
weight = 5

[[menu.primary]]
parent = "about"
identifier = "mission"
name = "Mission"
url = "/about/mission"
weight = 10

[[menu.primary]]
parent = "about"
identifier = "community"
name = "Community"
url = "/about/community"
weight = 11

[[menu.primary]]
parent = "about"
identifier = "history"
name = "History"
url = "/about/history"
weight = 12

[[menu.primary]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 6