backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "announcement" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Announcement" # Used in the UI, ie.: "New Post"
    folder: "site/content/announcements" # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    media_folder: "site/static/img"   # <--- Add this line
    public_folder: "img"  # <--- Add this line to ensure it uses global public_folder
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Photo Gallery"
        name: "photos"
        widget: "object"
        required: false
        fields: 
          - label: Heading
            name: heading
            widget: string
            required: false
          - label: Photos
            name: items
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
  - name: "convening" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Convening" # Used in the UI, ie.: "New Post"
    folder: "site/content/convenings" # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: text}
          - {label: Intro, name: intro, widget: markdown}
          - label: "Slideshow"
            name: slideshow
            widget: list
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Body, name: body, widget: markdown}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Text, name: text, widget: markdown}
              - {label: Image, name: imageUrl, widget: image}
      - file: "site/content/about/vision/_index.md"
        label: "Vision Page"
        name: "vision"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: intro, widget: text, required: false}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/about/history/_index.md"
        label: "History Page"
        name: "history"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: intro, widget: text, required: false}
          - {label: Body, name: body, widget: markdown}
          - label: Photos
            name: photos
            widget: object
            required: false
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Images
                name: items
                widget: list
                fields:
                  - {label: Image, name: image, widget: image}
      - file: "site/content/about/community/_index.md"
        label: "Community Page"
        name: "community"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: intro, widget: string, required: false}
          - {label: Intro, name: text, widget: text, required: false}
          - {label: Body, name: body, widget: markdown}
          - label: Staff
            name: staff
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Members
                name: items
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Title, name: org, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Bio, name: bio, widget: markdown}
          - label: Board
            name: board
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Members
                name: items
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Organization, name: org, widget: string}
                  - {label: Location, name: loc, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Bio, name: bio, widget: markdown}
          - label: Organizations
            name: orgs
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Org
                name: items
                widget: list
                fields:
                  - {label: Link, name: link, widget: string}
                  - {label: Text, name: text, widget: markdown}
                  - {label: Image, name: image, widget: image}
          - label: Partners
            name: partners
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Partnerships
                name: items
                widget: list
                fields:
                  - {label: Link, name: link, widget: string}
                  - {label: Text, name: text, widget: markdown}
                  - {label: Image, name: image, widget: image}
      - file: "site/content/grants/_index.md"
        label: "Grants Page"
        name: "grants"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - {label: Button, name: cta, widget: string, required: false}
          - {label: Button Link, name: link, widget: string, required: false}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/resources/_index.md"
        label: "Resources Page"
        name: "resources"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - {label: Body, name: body, widget: markdown}
          - label: Organizations
            name: orgs
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Org
                name: items
                widget: list
                fields:
                  - {label: Link, name: link, widget: string}
                  - {label: Text, name: text, widget: markdown}
                  - {label: Image, name: image, widget: image}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: text}
      - file: "site/hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
